# Generated by Django 4.0 on 2024-03-28 15:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mcfcarbrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Name', models.CharField(max_length=100)),
                ('idbs', models.IntegerField()),
                ('creationdate', models.DateField()),
                ('changedate', models.DateField()),
                ('mcfcode', models.CharField(default='id', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='z_avtobrand',
            fields=[
                ('BrandID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='z_avtocolor',
            fields=[
                ('ColorID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='z_avtomodel',
            fields=[
                ('ModelID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.z_avtobrand')),
            ],
        ),
        migrations.CreateModel(
            name='mcfcarmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Name', models.CharField(max_length=100)),
                ('idbs', models.IntegerField()),
                ('creationdate', models.DateField()),
                ('changedate', models.DateField()),
                ('mcfcode', models.CharField(default='id', max_length=100)),
                ('carbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.mcfcarbrand')),
                ('changeauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_mcfcarmodels', to='auto.user')),
                ('creationauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mcfcarmodels', to='auto.user')),
            ],
        ),
        migrations.CreateModel(
            name='mcfcarcolor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Name', models.CharField(max_length=100)),
                ('idbs', models.IntegerField()),
                ('creationdate', models.DateField()),
                ('changedate', models.DateField()),
                ('isdeleted', models.BooleanField()),
                ('changeauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_mcfcarcolors', to='auto.user')),
                ('creationauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mcfcarcolors', to='auto.user')),
            ],
        ),
        migrations.AddField(
            model_name='mcfcarbrand',
            name='changeauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_mcfcarbrands', to='auto.user'),
        ),
        migrations.AddField(
            model_name='mcfcarbrand',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.country'),
        ),
        migrations.AddField(
            model_name='mcfcarbrand',
            name='creationauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mcfcarbrands', to='auto.user'),
        ),
    ]
