# Generated by Django 4.0 on 2024-03-28 15:32

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionAudit',
            fields=[
                ('AuditID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('ActionID', models.IntegerField()),
                ('Sign', models.CharField(max_length=1)),
                ('OperationID', models.IntegerField()),
                ('OperDate', models.DateField()),
                ('ContractID', models.IntegerField()),
                ('AmountTypeID', models.IntegerField()),
                ('ActionTypeID', models.IntegerField()),
                ('PaymentTypeID', models.IntegerField()),
                ('IssueDate', models.DateField()),
                ('RepaymentDate', models.DateField()),
                ('IsOutBalance', models.BooleanField()),
                ('AmountLocalCur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AmountForeignCur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AuditDate', models.DateTimeField(auto_now_add=True)),
                ('procedureAudID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OperationAudit',
            fields=[
                ('AuditID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('OperationID', models.IntegerField()),
                ('Type', models.CharField(max_length=255)),
                ('Version', models.IntegerField()),
                ('OperDate', models.DateField()),
                ('TimeInMillis', models.BigIntegerField()),
                ('ContractID', models.IntegerField()),
                ('DocumentID', models.IntegerField()),
                ('AmountTypeID', models.IntegerField()),
                ('ActionTypeID', models.IntegerField()),
                ('PaymentTypeID', models.IntegerField()),
                ('IsOutBalance', models.BooleanField()),
                ('FundTransactionID', models.IntegerField()),
                ('TotalLocalCur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalForeignCur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RealDate', models.DateField()),
                ('IsAutoAccept', models.BooleanField()),
                ('CollateralID', models.IntegerField()),
                ('CollateralActionTypeID', models.IntegerField()),
                ('StoringPlaceID', models.IntegerField()),
                ('AuditDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureAud',
            fields=[
                ('procedureAudID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('ContractID', models.IntegerField()),
                ('ProcedureName', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(default=django.db.models.fields.DateTimeField)),
            ],
        ),
        migrations.CreateModel(
            name='TrancheAudit',
            fields=[
                ('AuditID', models.AutoField(primary_key=True, serialize=False)),
                ('TrancheID', models.IntegerField()),
                ('UserID', models.IntegerField()),
                ('Version', models.IntegerField()),
                ('ScheduleID', models.IntegerField()),
                ('IssueDate', models.DateField()),
                ('RepaymentDate', models.DateField()),
                ('Principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsLgot', models.CharField(max_length=1)),
                ('AuditDate', models.DateTimeField(auto_now_add=True)),
                ('procedureAudID', models.IntegerField()),
            ],
        ),
    ]
